### ISSUE TITLE
Some question and suggestion

### ISSUE THREAD

**Issue by beiyanpiki** [duanxr/PTCG-CHS-Datasets#2]
Hello.

Many thanks for creating and maintaining this project. I have some questions and suggestions.

- New Sword & Shield PROMO gym cards have been added, can they be synchronized?

- In the future Scarlet&Violet environment, **Pokemon Tools** have been categorized separately from **Items**. Should we consider adding a dedicated `trainerType` and `trainerTypeText` for Pokemon Tools to streamline conditional searches?

- Could we consider adding a field to distinguish cards with identical names but different effects? Currently, `nameSamePokemonId` field partially addresses this, but it falls short in cases like *CS1bC-071* and *CS2aC-084*, both being named "Zacian"  but these cards have different ability and attacks.

- Field naming is inconsistent with official rulebook, like: 
    - `feature` -> `ability`
    - `ability` -> `attack`

**Comment by duanxr** [comment]
Thanks for pointing it out, the new data has been added.
However, the data structure of this dataset comes from an official application. To my knowledge, several projects (including mine) are already using it. Changing the data structure would mean redeveloping these applications. Since the Simplified Chinese Version of PTCG is still in the SWSH, there are no plans to make changes until the SV arrives.

**Comment by duanxr** [comment]
I'm unclear about what you're seeking in your third question, since PTCG rules allow a maximum of only four cards with the same name, regardless of their abilities.

- If you're trying to determine whether two cards are identical, match their collection number and card number.
- If you're trying to determine whether two cards are deemed the same by game rules, simply match their names.
- If you're aiming to identify cards that have been reprinted from other collections, an image embedding model might be helpful.

**Comment by beiyanpiki** [comment]
Hi @duanxr 

Thank you for your response . I'm sorry didn't explain the third issue clearly, it somewhat different from the solutions you've listed above. 

#### For example:

There have two card both name 'Zacian', but they dont have same **attack**(or **effect**, **hp**, **energy type**, **ability**, **retreatcost**, etc..), ofc they have different image:

```
# Card A
苍响 / CS1bC-102
HP: 120
Attack: [
    咬碎 CCC 40 抛掷1次硬币如果为正面，则选择附着于对手战斗宝可梦身上的1个能量，放于弃牌区
    金属利刃 MMMC 190 选择附着于这只宝可梦身上的3个能量，放于弃牌区
]
weakness: R x2
resistant: G -30
retreatcost: 2

---

# Card B
苍响 / CS2aC-084
HP: 120
Attack:[
    能量气流 MC 30 选择自己弃牌区中的1张[钢] 能量，附着于这只宝可梦身上
    粉碎利刃 MMC 120 抛掷1次硬币如果为反面，则选择附着于这只宝可梦身上的2个能量，放于弃牌区
] 
weakness: R x2
resistant: G -30
retreatcost: 2
```


In standard rules, they have same name but different effect, Card A and Card B can only have a maximum of 4 copies in the deck (A+B<=4). 

In some scenarios, such as deck analysis, I need to **merge cards with the same effect rather than cards with the same name**. For now, Item, Pokemon Tools, Supporter, Special Energy with the same name always have the same effect(in CHS), so I can differentiate them through 'nameSamePokemonId'. But Pokemon Card like Card A and Card B have same `nameSamePokemonId` that I can not directly distinguish them.

**Comment by duanxr** [comment]
You can create your own "abilitySamePokemonId" by combining nameSamePokemonId with a hash of their ability names.

**Comment by beiyanpiki** [comment]
Thank you for your solution😊. 

BTW, I found that CSMPiC-010 is missing retreatCost, can you fix it? (Official app is also missing this field.)

**Comment by duanxr** [comment]
> Thank you for your solution😊.
> 
> BTW, I found that CSMPiC-010 is missing retreatCost, can you fix it? (Official app is also missing this field.)

Fixed.
